### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by nicofff** [y-ken/fluent-plugin-geoip#22]
This is probably a problem with the underling geoip database, but ipv6 addresses fail to resolve.

**Comment by y-ken** [comment]
Hi @nicofff 

Thank you for feature request.
It seems not hard to support country geo locate for IPv6 because Maxmind has provided GeoCityLite for IPv6.

I'm glad to support that soon, but I don't have a enough time to do that for now.
If you have a chanse to implement it, pull requests are very welcome!

**Comment by okkez** [comment]
IPv6 is supported with GeoIP2.
