### ISSUE TITLE
multiple ip addresses when using x-forwarded_for

### ISSUE THREAD

**Issue by vukomir** [y-ken/fluent-plugin-geoip#88]
#### Problem

If a request goes through multiple proxies, the IP addresses of each successive proxy is listed. This means, the right-most IP address is the IP address of the most recent proxy and the left-most IP address is the IP address of the originating client.

error
dump an error event: error_class=GeoIP2::Error error="getaddrinfo failed: Name or service not known" location="/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-geoip-1.3.1/lib/fluent/plugin/filter_geoip.rb:175:in `lookup'" 
...

#### Steps to replicate

X-Forwarded-For: 203.0.113.195, 70.41.3.18, 150.172.238.178

#### Expected Behavior

is there are multiple ip addresses in the filed that contains ip address it should use the first ip
...

#### Your environment

'fluent-plugin-concat' version '2.4.0'
'fluent-plugin-dedot_filter' version '1.0.0'
'fluent-plugin-detect-exceptions' version '0.0.13'
'fluent-plugin-elasticsearch' version '4.0.7'
'fluent-plugin-geoip' version '1.3.1'
'fluent-plugin-grok-parser' version '2.6.1'
'fluent-plugin-json-in-json-2' version '1.0.2'
'fluent-plugin-kubernetes_metadata_filter' version '2.3.0'
'fluent-plugin-multi-format-parser' version '1.0.0'
'fluent-plugin-prometheus' version '1.6.1'
'fluent-plugin-record-modifier' version '2.0.1'
'fluent-plugin-rewrite' version '0.1.1'
'fluent-plugin-rewrite-tag-filter' version '2.2.0'
'fluent-plugin-systemd' version '1.0.2'
'fluentd' version '1.10.1'

**Comment by okkez** [comment]
You can apply [filter record_transformer](https://docs.fluentd.org/filter/record_transformer) plugin before this plugin.

**Comment by harshpandit007** [comment]
@vukomir : I'm having the similar issue with x_forwarded_for. did you figure it out using record_transformer?

**Comment by harshpandit007** [comment]
With the help of @okkez and my friend @francisco-andrade, I was able to solve this. Just posting my solution here for future references:
```
#Grep first ip from x_forwarded_for list and put it into a new variable i.e. x_forwarded_for_ip
<filter nginx.access>
  @type record_transformer
  enable_ruby
  <record>
     x_forwarded_for_ip ${record["x_forwarded_for"].split(',')[0]}
  </record>
</filter>

# We use the above-created x_forwarded_for_ip in the geoip plugin as this expects only one IP in the input string.
<filter nginx.access>
  @type geoip
  backend_library geoip2_c
  # Set key name for the client ip address values
  geoip_lookup_keys     x_forwarded_for_ip
  # Specify key name for the country_code values
  <record>
    city ${city.names.en["x_forwarded_for_ip"]}
    latitude ${location.latitude["x_forwarded_for_ip"]}
    longitude ${location.longitude["x_forwarded_for_ip"]}
    country_code ${country.iso_code["x_forwarded_for_ip"]}
    country_name ${country.names.en["x_forwarded_for_ip"]}
    region_code ${subdivisions.0.iso_code["x_forwarded_for_ip"]}
    region_name ${subdivisions.0.names.en["x_forwarded_for_ip"]}
  </record>
</filter>
```

**Comment by younsl** [comment]
My logging system stack, running on Kubernetes, was composed of the following components: source pods sending logs to Fluent Bit (running as a DaemonSet), which then forwarded them to Fluentd (as a StatefulSet), followed by OpenSearch for storage, and finally Kibana for visualization.

I encountered a similar issue where Fluentd showed the error: `GeoIP2::Error error="getaddrinfo failed: Name or service not known"`. This prevented logs from certain pods from reaching OpenSearch.

Upon checking the logs, I found the IP address field formatted like `"ip":"[218.xxx.xx.xx]"`, enclosed in square brackets. The `fluent-plugin-geoip` expects a plain IP address string (e.g., `"218.xxx.xx.xx"`) and failed because of the brackets.

## How to Fix

There are two main ways to address this:

1.  **Modify Application Logging (This is what I did):** I adjusted the application code to log the IP address as a simple string, without the surrounding square brackets (e.g., `"218.xxx.xx.xx"`). This resolved the error.

2.  **Use Fluentd's [`record_transformer`](https://docs.fluentd.org/filter/record_transformer) Filter (Alternative):** You can configure Fluentd to automatically remove the brackets from the `ip` field before it reaches the geoip plugin.

    **Important Note:** The configuration below modifies the `ip` field *in place*. It replaces the original value (like `"[218.xxx.xx.xx]"`) with the processed value (`"218.xxx.xx.xx"`). Be mindful that the original format will be lost.

    Example Fluentd filter configuration:
    ```fluentd
    <filter kube.**>
      @type record_transformer
      enable_ruby true
      <record>
        ip ${record["ip"].gsub(/\[|\]/, '')}
      </record>
    </filter>
    ```

## Conclusion

The `GeoIP2::Error error="getaddrinfo failed: Name or service not known"` error occurred because the `fluent-plugin-geoip` received an IP address in an unexpected format (e.g., `"[1.2.3.4]"`).

To fix this, you can either:
1.  Ensure your application logs IP addresses as plain strings (e.g., `"1.2.3.4"`).
2.  Use Fluentd's [`record_transformer`](https://docs.fluentd.org/filter/record_transformer) filter to clean the IP address field, remembering that this modifies the original data.
